name: Publish

on:
  release:
    types:
      - created

jobs:

  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Install Poetry
        uses: snok/install-poetry@v1.1.2

      - name: Set Poetry config
        run: |
          poetry config pypi-token.pypi ${{ secrets.pypi_token }}

      - name: Install Dependencies
        run: poetry install

      - name: Publish to PyPI
        run: poetry publish --build
